feat(repo_blob): add CatFileBlob
gogs/git-module pull request #79
Opened 2022-06-11 11:41 UTC by jonatan5524

### Describe the pull request

Add a method that returns any Blob object by its corresponding hash.

Link to the issue: gogs/gogs#5979

### Checklist

- [ ] I agree to follow the [Code of Conduct](https://go.dev/conduct) by submitting this pull request.
- [ ] I have read and acknowledge the [Contributing guide](https://github.com/gogs/gogs/blob/main/.github/CONTRIBUTING.md).
- [ ] I have added test cases to cover the new code.

2022-06-20 23:13 UTC, unknwon requested changes
Thanks for the PR! Just one problem.

2022-06-20 23:13 UTC, unknwon commented on repo_blob.go
> +// Copyright 2015 The Gogs Authors. All rights reserved.
```suggestion
// Copyright 2022 The Gogs Authors. All rights reserved.
```

2022-06-20 23:13 UTC, unknwon commented on repo_blob_test.go
> +// Copyright 2020 The Gogs Authors. All rights reserved.
```suggestion
// Copyright 2022 The Gogs Authors. All rights reserved.
```

2022-06-20 23:13 UTC, unknwon commented on repo_blob_test.go
> +		}
```suggestion
		require.NoError(t, err)
```

2022-06-20 23:13 UTC, unknwon commented on repo_blob.go
> +			id:   MustIDFromString(rev),
There is no guarantee the `rev` being passed here is always a full-length SHA, I think we need to same thing as in `CatFileCommit`:

https://github.com/gogs/git-module/blob/a2567c624d4263a01df4a5405ebe065a9f96e0c3/repo_commit.go#L95-L98

2022-06-20 23:14 UTC, unknwon commented on repo_blob_test.go
> +
```suggestion
```

2022-06-20 23:14 UTC, unknwon commented on repo_blob_test.go
> +	"github.com/stretchr/testify/assert"
```suggestion
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
```

2022-06-23 10:26 UTC, unknwon commented on repo_blob.go
> +	revHash, err := r.RevParse(rev, RevParseOptions{Timeout: opt.Timeout}) //nolint
```suggestion
	rev, err := r.RevParse(rev, RevParseOptions{Timeout: opt.Timeout}) //nolint
```

You can reuse the same variable.

2022-06-23 10:26 UTC, unknwon commented on repo_blob_test.go
> +		b, err := testrepo.CatFileBlob("021a721a61a1de65865542c405796d1eb985f784")
Could you also add a test case like `testrepo.CatFileBlob("021a721")`?

2022-06-23 10:26 UTC, unknwon commented
Thanks for the followup!

2022-06-23 12:17 UTC, unknwon approved these changes

2022-06-23 12:18 UTC, unknwon commented on repo_blob.go
> +	typ, err := repo.CatFileType(revHash)
```suggestion
	typ, err := repo.CatFileType(rev)
```

2022-06-23 12:21 UTC, unknwon commented on repo_blob.go
> +func (repo *Repository) CatFileBlob(rev string) (*Blob, error) {
```suggestion
func (r *Repository) CatFileBlob(rev string) (*Blob, error) {
```

2022-06-23 12:21 UTC, unknwon commented on repo_blob.go
> +	typ, err := repo.CatFileType(rev)
```suggestion
	typ, err := r.CatFileType(rev)
```

2022-06-23 12:21 UTC, unknwon commented on repo_blob.go
> +				repo: repo,
```suggestion
				repo: r,
```

2022-06-23 12:23 UTC, unknwon commented
There are too many compile errors, could you fix that?

2022-06-23 12:29 UTC, jonatan5524 commented
> There are too many compile errors... could you fix that?

yes, I am not working from home, working from web, because of that there are errors, I will take care of it.

2022-06-24 10:11 UTC, jonatan5524 commented
fixed the compile errors @unknwon , sorry for the delay and the bad work, I had a busy week and could work on it properly only now.

2022-06-24 10:25 UTC, unknwon commented
No worries at all! I’ll take another look.

2022-06-25 09:31 UTC, merged

2022-06-25 09:31 UTC, unknwon commented
https://github.com/gogs/git-module/releases/tag/v1.7.0 has been tagged for this merge.